[versions]
minSdk = "21"
compileSdk = "34"
targetSdk = "34"

androidgradleplugin = "8.8.2"
kotlin = "2.1.21"
ktlint = "1.7.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-emoji-appcompat = { module = "androidx.emoji:emoji-appcompat", version = "1.1.0" }
androidx-emoji2 = { module = "androidx.emoji2:emoji2", version = "1.5.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
espressocoreutils = { module = "com.vanniktech:espresso-core-utils", version = "0.4.0" }
falcon = { module = "com.jraska:falcon", version = "2.2.0" }
junitintegrationrules = { module = "com.vanniktech:junit4-android-integration-rules", version = "0.3.0" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
material = { module = "com.google.android.material:material", version = "1.12.0" }
plugin-android-cache-fix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version = "3.0.1" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.0.0" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.13.0" }
plugin-metalava = { module = "me.tylerbwong.gradle.metalava:plugin", version = "0.4.0-alpha03" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.34.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
screengrab = { module = "tools.fastlane:screengrab", version = "2.1.1" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
ui = { module = "com.vanniktech:ui", version = "0.10.0" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
dependencygraphgenerator = { id = "com.vanniktech.dependency.graph.generator", version = "0.8.0" }
